### ISSUE TITLE
adapter.yaml causes an CFn error

### ISSUE THREAD

**Issue by gusmasaakisuga** [Codemill/av-ecs-cloudformation#7]
https://github.com/Codemill/av-ecs-cloudformation/commit/5c525051ca4f948c30f47adf9528ca1cd561d68b

This causes an CFn template error with the following message:
 1/19/2021, 9:49:22 AM - Template contains errors.: Template error: variable names in Fn::Sub syntax must contain only alphanumeric characters, underscores, periods, and colons

**Comment by gusmasaakisuga** [comment]
For a temporary solution, 

alter 
-Dvertx.hazelcast.config=${CLUSTER_XML:-/opt/cluster.xml} in the line at
https://github.com/Codemill/av-ecs-cloudformation/blob/a6810a69729d675ee742fdb9864a66622a3b8070/adapter.yaml#L138

to 
-Dvertx.hazelcast.config=/opt/cluster.xml
seems to be working (at least CloudFormation template execution).  But not the right approach so please take a look into it.

**Comment by andreasolund** [comment]
Fixed in https://github.com/Codemill/av-ecs-cloudformation/commit/8a14f20e5704aed29fc47a8e14932f68ec02b249
